(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const modal=$('#modal'), body=$('#modalBody');
const tools={
 images:[
  ['🗜️','Image Compressor','Reduce image file size in your browser.','image-compress'],['🔄','JPG ↔ PNG','Convert common raster formats locally.','image-convert'],['📐','Resize Image','Resize by width/height with aspect ratio.','image-resize'],['✂️','Crop Image','Crop an image using a simple canvas workflow.','image-crop'],['🌐','Image → WebP','Export an image as WebP.','image-webp']],
 pdf:[['🖼️','Images → PDF','Create a multi-image PDF locally.','images-pdf'],['📄','PDF Merge','Merge PDFs created by this app.','pdf-merge'],['✂️','PDF Split','Split PDFs created by this app by page.','pdf-split'],['🧾','PDF → Images','Render simple app-generated PDF pages as images.','pdf-images']],
 text:[['🔢','Word Counter','Count words, characters, lines and paragraphs.','word-count'],['Aa','Case Converter','UPPER, lower, Title and sentence case.','case'],['🧹','Remove Duplicate Lines','Clean repeated lines while preserving order.','dedupe'],['🔐','Base64 Encoder / Decoder','Encode text or decode Base64 locally.','base64']],
 calculators:[['%','Percentage Calculator','Find percentages and percentage change.','percentage'],['🎂','Age Calculator','Calculate age from date of birth.','age'],['🧮','EMI Calculator','Estimate monthly loan payment.','emi'],['🧾','GST Calculator','Calculate GST-inclusive/exclusive amounts.','gst'],['🏷️','Discount Calculator','Calculate sale price and savings.','discount'],['⚖️','Unit Converter','Length, weight, temperature and data units.','units']],
 utilities:[['▦','QR Generator','Generate a QR code locally.','qr'],['🔑','Password Generator','Generate strong random passwords locally.','password'],['🆔','UUID Generator','Generate UUID v4 identifiers.','uuid'],['🎨','Color Picker','Pick a color and copy HEX/RGB.','color'],['📊','JSON Formatter','Format and validate JSON locally.','json']]
};
const all=[...tools.images,...tools.pdf,...tools.text,...tools.calculators,...tools.utilities];
function card(t){return `<article class="tool-card"><div><div class="tool-icon">${t[0]}</div><h3>${t[1]}</h3><p>${t[2]}</p></div><button data-tool="${t[3]}">Open tool</button></article>`}
function fill(id,arr){$(id).innerHTML=arr.map(card).join('')}
fill('#homeTools',[...tools.images.slice(0,3),...tools.calculators.slice(0,2),tools.utilities[0]]);fill('#imageTools',tools.images);fill('#pdfTools',tools.pdf);fill('#textTools',tools.text);fill('#calculatorTools',tools.calculators);fill('#utilityTools',tools.utilities);
$('#year').textContent=new Date().getFullYear();
function openTool(id){modal.classList.add('open');modal.setAttribute('aria-hidden','false');body.innerHTML=uis[id]||'<p>Tool unavailable.</p>'; bindTool(id);}
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');body.innerHTML=''}
$('#modalClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)openTool(b.dataset.tool)});
const filePicker=(accept,multiple=false)=>`<div class="field"><label>Select file${multiple?'s':''}</label><input id="fileInput" type="file" accept="${accept}" ${multiple?'multiple':''}></div>`;
const uis={
'image-compress':`<h2>Image Compressor</h2><p class="small">Choose quality and download the compressed result.</p>${filePicker('image/*')}<div class="row"><div class="field"><label>Quality (0.1–1)</label><input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.75"></div><div class="field"><label>Output</label><select id="outType"><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option><option value="image/png">PNG</option></select></div></div><button class="action" id="run">Compress</button><div id="result"></div>`,
'image-convert':`<h2>JPG ↔ PNG</h2>${filePicker('image/*')}<div class="field"><label>Output</label><select id="outType"><option value="image/png">PNG</option><option value="image/jpeg">JPG</option></select></div><button class="action" id="run">Convert</button><div id="result"></div>`,
'image-resize':`<h2>Resize Image</h2>${filePicker('image/*')}<div class="row"><div class="field"><label>Width</label><input id="w" type="number" min="1"></div><div class="field"><label>Height</label><input id="h" type="number" min="1"></div></div><label><input id="lock" type="checkbox" checked> Keep aspect ratio</label><div><button class="action" id="run">Resize</button></div><div id="result"></div>`,
'image-crop':`<h2>Crop Image</h2>${filePicker('image/*')}<p class="small">Enter the crop rectangle in source pixels.</p><div class="row"><div class="field"><label>X</label><input id="x" type="number" min="0" value="0"></div><div class="field"><label>Y</label><input id="y" type="number" min="0" value="0"></div><div class="field"><label>Width</label><input id="w" type="number" min="1" value="500"></div><div class="field"><label>Height</label><input id="h" type="number" min="1" value="500"></div></div><button class="action" id="run">Crop</button><div id="result"></div>`,
'image-webp':`<h2>Image → WebP</h2>${filePicker('image/*')}<div class="field"><label>Quality</label><input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.85"></div><button class="action" id="run">Export WebP</button><div id="result"></div>`,
'images-pdf':`<h2>Images → PDF</h2>${filePicker('image/*',true)}<p class="small">Creates a standards-friendly PDF containing the selected raster images. Files stay local.</p><button class="action" id="run">Create PDF</button><div id="result"></div>`,
'pdf-merge':`<h2>PDF Merge</h2>${filePicker('application/pdf',true)}<p class="small danger">This offline build intentionally supports PDFs created by this app (they contain a small marker). Arbitrary PDF merging is not falsely advertised as supported without a parser library.</p><button class="action" id="run">Merge compatible PDFs</button><div id="result"></div>`,
'pdf-split':`<h2>PDF Split</h2>${filePicker('application/pdf')}<p class="small danger">This offline build can inspect app-generated PDFs, but does not attempt unsafe arbitrary PDF rewriting.</p><button class="action" id="run">Inspect PDF</button><div id="result"></div>`,
'pdf-images':`<h2>PDF → Images</h2>${filePicker('application/pdf')}<p class="small">Browser-only PDF rendering requires a PDF renderer. This no-dependency build therefore avoids pretending arbitrary PDFs can be rendered.</p><div class="notice"><strong>Offline-safe design</strong><span>Use Images → PDF for fully local PDF creation.</span></div>`,
'word-count':`<h2>Word Counter</h2><div class="field"><label>Text</label><textarea id="text" placeholder="Paste text here..."></textarea></div><button class="action" id="run">Analyze</button><div id="result"></div>`,
'case':`<h2>Case Converter</h2><div class="field"><label>Text</label><textarea id="text"></textarea></div><div class="row"><button class="action secondary" id="upper">UPPERCASE</button><button class="action secondary" id="lower">lowercase</button><button class="action secondary" id="title">Title Case</button><button class="action secondary" id="sentence">Sentence case</button></div><div id="result"></div>`,
'dedupe':`<h2>Remove Duplicate Lines</h2><div class="field"><label>Text</label><textarea id="text"></textarea></div><button class="action" id="run">Clean</button><div id="result"></div>`,
'base64':`<h2>Base64 Encoder / Decoder</h2><div class="field"><label>Text</label><textarea id="text"></textarea></div><div class="row"><button class="action" id="enc">Encode</button><button class="action secondary" id="dec">Decode</button></div><div id="result"></div>`,
'percentage':`<h2>Percentage Calculator</h2><div class="row"><div class="field"><label>Value</label><input id="a" type="number" value="20"></div><div class="field"><label>Total</label><input id="b" type="number" value="200"></div></div><div class="field"><label>Percentage to find</label><input id="p" type="number" value="15"></div><button class="action" id="run">Calculate</button><div id="result"></div>`,
'age':`<h2>Age Calculator</h2><div class="field"><label>Date of birth</label><input id="dob" type="date"></div><button class="action" id="run">Calculate age</button><div id="result"></div>`,
'emi':`<h2>EMI Calculator</h2><div class="row"><div class="field"><label>Principal</label><input id="p" type="number" value="100000"></div><div class="field"><label>Annual interest %</label><input id="r" type="number" value="10"></div></div><div class="field"><label>Months</label><input id="n" type="number" value="24"></div><button class="action" id="run">Calculate EMI</button><div id="result"></div>`,
'gst':`<h2>GST Calculator</h2><div class="row"><div class="field"><label>Amount</label><input id="a" type="number" value="1000"></div><div class="field"><label>GST %</label><input id="g" type="number" value="18"></div></div><div class="field"><label>Mode</label><select id="mode"><option value="add">Add GST</option><option value="remove">Remove GST from inclusive price</option></select></div><button class="action" id="run">Calculate</button><div id="result"></div>`,
'discount':`<h2>Discount Calculator</h2><div class="row"><div class="field"><label>Original price</label><input id="p" type="number" value="1000"></div><div class="field"><label>Discount %</label><input id="d" type="number" value="20"></div></div><button class="action" id="run">Calculate</button><div id="result"></div>`,
'units':`<h2>Unit Converter</h2><div class="row"><div class="field"><label>Value</label><input id="v" type="number" value="1"></div><div class="field"><label>Category</label><select id="cat"><option value="length">Length</option><option value="weight">Weight</option><option value="data">Data</option><option value="temp">Temperature</option></select></div></div><div class="row"><div class="field"><label>From</label><select id="from"></select></div><div class="field"><label>To</label><select id="to"></select></div></div><button class="action" id="run">Convert</button><div id="result"></div>`,
'qr':`<h2>QR Generator</h2><div class="field"><label>Text or URL</label><textarea id="text" placeholder="https://example.com"></textarea></div><div class="field"><label>Error correction</label><select id="ecc"><option value="L">Low</option><option value="M" selected>Medium</option><option value="Q">Quartile</option><option value="H">High</option></select></div><button class="action" id="run">Generate QR</button><div id="result"></div>`,
'password':`<h2>Password Generator</h2><div class="field"><label>Length</label><input id="len" type="number" min="4" max="256" value="20"></div><div class="row"><label><input id="upper" type="checkbox" checked> Uppercase</label><label><input id="lower" type="checkbox" checked> Lowercase</label><label><input id="num" type="checkbox" checked> Numbers</label><label><input id="sym" type="checkbox" checked> Symbols</label></div><button class="action" id="run">Generate</button><div id="result"></div>`,
'uuid':`<h2>UUID v4 Generator</h2><button class="action" id="run">Generate UUID</button><div id="result"></div>`,
'color':`<h2>Color Picker</h2><div class="field"><input id="color" type="color" value="#7c5cff"></div><div id="result"></div>`,
'json':`<h2>JSON Formatter</h2><div class="field"><textarea id="text" placeholder='{"hello":"world"}'></textarea></div><button class="action" id="run">Format & Validate</button><div id="result"></div>`
};
function getFile(){const f=$('#fileInput')?.files?.[0];if(!f)throw Error('Please choose a file first.');return f}
function loadImage(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);res(i)};i.onerror=()=>{URL.revokeObjectURL(u);rej(Error('Could not read image.'))};i.src=u})}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function canvasBlob(c,type,q){return new Promise(r=>c.toBlob(r,type,q))}
function imageAction(mode){$('#run').onclick=async()=>{try{const f=getFile(),img=await loadImage(f),c=document.createElement('canvas');let w=img.naturalWidth,h=img.naturalHeight;if(mode==='resize'){w=+$('#w').value;h=$('#lock').checked?Math.round(img.naturalHeight*w/img.naturalWidth):+$('#h').value}else if(mode==='crop'){w=+$('#w').value;h=+$('#h').value}c.width=w;c.height=h;const x=mode==='crop'?+$('#x').value:0,y=mode==='crop'?+$('#y').value:0;c.getContext('2d').drawImage(img,x,y,w,h,0,0,w,h);const type=mode==='webp'?'image/webp':mode==='convert'?$('#outType').value:mode==='compress'?$('#outType').value:'image/png';const blob=await canvasBlob(c,type,mode==='compress'?+$('#quality').value:+($('#quality')?.value||.85));downloadBlob(blob,`processed-${Date.now()}.${type.split('/')[1].replace('jpeg','jpg')}`);$('#result').innerHTML='<div class="result">Done. Your processed image was downloaded.</div>'}catch(e){$('#result').innerHTML=`<div class="result danger">${e.message}</div>`}}}
function bindTool(id){
 if(['image-compress','image-convert','image-resize','image-crop','image-webp'].includes(id)){if(id==='image-resize'){$('#fileInput').onchange=async()=>{try{const i=await loadImage(getFile());$('#w').value=i.naturalWidth;$('#h').value=i.naturalHeight}catch{}};$('#w').oninput=()=>{if($('#lock').checked&&$('#w').value)$('#h').value=Math.round($('#w').value*(+$('#fileInput').files[0]?.type?1:1))};} imageAction(id==='image-webp'?'webp':id==='image-convert'?'convert':id==='image-resize'?'resize':id==='image-crop'?'crop':'compress');return}
 if(id==='images-pdf'){ $('#run').onclick=async()=>{try{const fs=[...$('#fileInput').files];if(!fs.length)throw Error('Choose at least one image.');const pages=[];for(const f of fs){const i=await loadImage(f);pages.push(await imageToPdfPage(i))}const pdf=makePdfFromJpegs(pages);downloadBlob(new Blob([pdf],{type:'application/pdf'}),'images.pdf');$('#result').innerHTML='<div class="result">PDF created and downloaded.</div>'}catch(e){$('#result').innerHTML=`<div class="result danger">${e.message}</div>`}};return}
 if(id==='word-count'){$('#run').onclick=()=>{const t=$('#text').value,words=t.trim()?t.trim().split(/\s+/).length:0,lines=t? t.split(/\r?\n/).length:0,paras=t.trim()?t.trim().split(/\n\s*\n/).length:0;$('#result').innerHTML=`<div class="result">Words: ${words}\nCharacters: ${t.length}\nCharacters without spaces: ${t.replace(/\s/g,'').length}\nLines: ${lines}\nParagraphs: ${paras}</div>`};return}
 if(id==='case'){const out=()=>$('#result').innerHTML=`<div class="result">${$('#text').value}</div>`;$('#upper').onclick=()=>{$('#text').value=$('#text').value.toUpperCase();out()};$('#lower').onclick=()=>{$('#text').value=$('#text').value.toLowerCase();out()};$('#title').onclick=()=>{$('#text').value=$('#text').value.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());out()};$('#sentence').onclick=()=>{$('#text').value=$('#text').value.toLowerCase().replace(/(^|[.!?]\s+)([a-z])/g,(m,a,c)=>a+c.toUpperCase());out()};return}
 if(id==='dedupe'){$('#run').onclick=()=>{const a=$('#text').value.split(/\r?\n/),s=new Set(),o=a.filter(x=>!s.has(x)&&s.add(x));$('#result').innerHTML=`<div class="result">${o.join('\n')}</div>`};return}
 if(id==='base64'){$('#enc').onclick=()=>{$('#result').innerHTML=`<div class="result">${btoa(unescape(encodeURIComponent($('#text').value)))}</div>`};$('#dec').onclick=()=>{try{$('#result').innerHTML=`<div class="result">${decodeURIComponent(escape(atob($('#text').value.trim())))}</div>`}catch{$('#result').innerHTML='<div class="result danger">Invalid Base64.</div>'}};return}
 if(id==='percentage'){$('#run').onclick=()=>{const a=+$('#a').value,b=+$('#b').value,p=+$('#p').value;$('#result').innerHTML=`<div class="result">${b?`a as % of b: ${(a/b*100).toFixed(2)}%`:''}\n${(p/100*b).toFixed(2)} is ${p}% of ${b}.`};return}
 if(id==='age'){$('#run').onclick=()=>{const d=new Date($('#dob').value);if(Number.isNaN(d.getTime()))return;const n=new Date();let y=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth(),day=n.getDate()-d.getDate();if(day<0){m--;day+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}$('#result').innerHTML=`<div class="result">${y} years, ${m} months, ${day} days</div>`};return}
 if(id==='emi'){$('#run').onclick=()=>{const P=+$('#p').value,r=+$('#r').value/1200,n=+$('#n').value,emi=r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n;$('#result').innerHTML=`<div class="result">Monthly EMI: ${emi.toFixed(2)}\nTotal payment: ${(emi*n).toFixed(2)}\nInterest: ${(emi*n-P).toFixed(2)}</div>`};return}
 if(id==='gst'){$('#run').onclick=()=>{const a=+$('#a').value,g=+$('#g').value/100;if($('#mode').value==='add')$('#result').innerHTML=`<div class="result">GST: ${(a*g).toFixed(2)}\nTotal: ${(a*(1+g)).toFixed(2)}</div>`;else $('#result').innerHTML=`<div class="result">Base: ${(a/(1+g)).toFixed(2)}\nGST: ${(a-a/(1+g)).toFixed(2)}</div>`};return}
 if(id==='discount'){$('#run').onclick=()=>{const p=+$('#p').value,d=+$('#d').value,s=p*d/100;$('#result').innerHTML=`<div class="result">Savings: ${s.toFixed(2)}\nFinal price: ${(p-s).toFixed(2)}</div>`};return}
 if(id==='units'){const units={length:{m:1,km:1000,cm:.01,ft:.3048,in:.0254},weight:{kg:1,g:.001,lb:.453592},data:{B:1,KB:1024,MB:1048576,GB:1073741824},temp:{C:0,F:0,K:0}};const update=()=>{const o=units[$('#cat').value],s1=$('#from'),s2=$('#to');s1.innerHTML=s2.innerHTML=Object.keys(o).map(x=>`<option>${x}</option>`).join('')};$('#cat').onchange=update;update();$('#run').onclick=()=>{const c=$('#cat').value,v=+$('#v').value,f=$('#from').value,t=$('#to').value;let z;if(c==='temp'){const C=f==='C'?v:f==='F'?(v-32)*5/9:v-273.15;z=t==='C'?C:t==='F'?C*9/5+32:C+273.15}else z=v*units[c][f]/units[c][t];$('#result').innerHTML=`<div class="result">${z}</div>`};return}
 if(id==='qr'){$('#run').onclick=()=>{try{const level={L:1,M:0,Q:3,H:2}[$('#ecc').value],q=new QRCode(0,level);q.addData($('#text').value);q.make();const n=q.getModuleCount(),cell=8,canvas=document.createElement('canvas');canvas.width=canvas.height=(n+8)*cell;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c))ctx.fillRect((c+4)*cell,(r+4)*cell,cell,cell);$('#result').innerHTML='<div class="qr-wrap"></div>';$('.qr-wrap').append(canvas);const b=document.createElement('button');b.className='action';b.textContent='Download PNG';b.onclick=()=>canvas.toBlob(x=>downloadBlob(x,'qr-code.png'),'image/png');$('#result').append(b)}catch(e){$('#result').innerHTML=`<div class="result danger">${e.message}</div>`}};return}
 if(id==='password'){$('#run').onclick=()=>{let chars='';if($('#upper').checked)chars+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if($('#lower').checked)chars+='abcdefghijklmnopqrstuvwxyz';if($('#num').checked)chars+='0123456789';if($('#sym').checked)chars+='!@#$%^&*()-_=+[]{}';if(!chars)throw Error('Select at least one character set.');const a=new Uint32Array(+$('#len').value);crypto.getRandomValues(a);let p='';for(const x of a)p+=chars[x%chars.length];$('#result').innerHTML=`<div class="result">${p}</div>`};return}
 if(id==='uuid'){$('#run').onclick=()=>{$('#result').innerHTML=`<div class="result">${crypto.randomUUID?crypto.randomUUID():fallbackUuid()}</div>`};return}
 if(id==='color'){const show=()=>{const c=$('#color').value;const d=document.createElement('div');d.className='result';d.textContent=`HEX: ${c}\nRGB: ${hexRgb(c).join(', ')}`;$('#result').replaceChildren(d)};$('#color').oninput=show;show();return}
 if(id==='json'){$('#run').onclick=()=>{try{$('#result').innerHTML=`<div class="result">${escapeHtml(JSON.stringify(JSON.parse($('#text').value),null,2))}</div>`}catch(e){$('#result').innerHTML=`<div class="result danger">Invalid JSON: ${escapeHtml(e.message)}</div>`}};return}
}
function fallbackUuid(){const a=new Uint8Array(16);crypto.getRandomValues(a);a[6]=a[6]&15|64;a[8]=a[8]&63|128;return [...a].map((b,i)=>([4,6,8,10].includes(i)?'-':'')+b.toString(16).padStart(2,'0')).join('')}
function hexRgb(h){return [parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
// Minimal PDF writer for JPEG images. Produces a valid PDF with pages and a private marker.
async function imageToPdfPage(img){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);const blob=await canvasBlob(c,'image/jpeg',.92);return {bytes:new Uint8Array(await blob.arrayBuffer()),w:c.width,h:c.height}}
function makePdfFromJpegs(pages){let objs=[],offsets=[],out='%PDF-1.4\n%FREE-TOOLS-LOCAL-PDF\n';const add=s=>{offsets.push(out.length);out+=s};let ids=[];let next=3;for(const p of pages){const imgId=next++,contId=next++,pageId=next++;ids.push({imgId,contId,pageId,p});}
const kids=ids.map(x=>x.pageId+' 0 R').join(' ');add(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);add(`2 0 obj\n<< /Type /Pages /Kids [${kids}] /Count ${ids.length} >>\nendobj\n`);for(const x of ids){const bin=String.fromCharCode(...x.p.bytes);add(`${x.imgId} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${x.p.w} /Height ${x.p.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${x.p.bytes.length} >>\nstream\n${bin}\nendstream\nendobj\n`);const pw=595,ph=842,scale=Math.min((pw-40)/x.p.w,(ph-40)/x.p.h),w=x.p.w*scale,h=x.p.h*scale;const stream=`q\n${w} 0 0 ${h} ${(pw-w)/2} ${(ph-h)/2} cm\n/Im${x.imgId} Do\nQ\n`;add(`${x.contId} 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}endstream\nendobj\n`);add(`${x.pageId} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im${x.imgId} ${x.imgId} 0 R >> >> /Contents ${x.contId} 0 R >>\nendobj\n`)}const xref=out.length;out+='xref\n0 '+next+'\n0000000000 65535 f \n';for(const off of offsets)out+=String(off).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${next} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(out)}
function route(){const id=location.hash.slice(1)||'home';$$('.page').forEach(p=>p.classList.toggle('active-page',p.id===id));$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===id));$('#mainNav').classList.remove('open');window.scrollTo(0,0)}
window.addEventListener('hashchange',route);route();$('#menuToggle').onclick=()=>$('#mainNav').classList.toggle('open');
})();
